// Generated by https://quicktype.io

export interface IConta {
    id:      string;
    usuario: string;
    senha:   string;
    cliente: Cliente;
}

export interface Cliente {
    id:    string;
    nome:  string;
    email: string;
}
